Dependencies: [[Batch_size]]

Default_vals:
       'Rank': [3000]
       'Batch_size': []
       'N_tries': [25]
       'Way': ['CCL GPU']

Path_to_datasets: '/workspace/datasets'
Path_to_csvs: '/workspace/csvs'
Path_to_svds: '/workspace/svds'