Dependencies: [['Batch_size', 'Rank']]

Default_vals:
       'Rank': [3000]
       'Batch_size': [10000]
       'N_tries': [5]
       'Way': ['heuristic']

Path_to_datasets: 'G:\datasets\Small'
Path_to_csvs: 'C:\Users\tanya\GitHub\Gromov-delta-estimation\results\csvs'
Path_to_svds: 'D:\DeltaEstimation\DeltaEstimation\SVD'
