DATASETS:
       'small': ['AMAZON_FASHION','All_Beauty','Appliances','Gift_Cards','Magazine_Subscriptions']
#       'medium': ['Digital_Music','Industrial_and_Scientific','Luxury_Beauty','Prime_Pantry','Software']
       'current': ['Grocery_and_Gourmet_Food', 'Arts_Crafts_and_Sewing', 'Office_Products']
#       'big': ['Arts_Crafts_and_Sewing','Automotive','Books','CDs_and_Vinyl','Cell_Phones_and_Accessories',
       'big': ['Clothing_Shoes_and_Jewelry','Electronics','Grocery_and_Gourmet_Food','Home_and_Kitchen','Kindle_Store','Movies_and_TV','Musical_Instruments','Office_Products','Patio_Lawn_and_Garden','Pet_Supplies','Sports_and_Outdoors','Tools_and_Home_Improvement','Toys_and_Games','Video_Games','Movielens_1m']







