Dependencies: [['Batch_size', 'Rank', 'Way']]

Default_vals:
       'Rank': [3000]
       'Batch_size': [10000]
       'N_tries': [5]
       'Way': ['heuristic']

Path_to_datasets: 'Path to datasets'
Path_to_csvs: '\results\csvs'
Path_to_svds: 'Path to file with svds'
